using UnityEngine;
using TMPro;
 
public class TextoDa침oTablero : MonoBehaviour
{
    [SerializeField] TextMeshProUGUI m_Object;
    [SerializeField] GameObject textoCompleto;
    [SerializeField] bool isPlayer;
   
    void Start()
    {
          m_Object.GetComponent<TMPro.TextMeshProUGUI>().text = "Inici칩 sin problemas";
    }

    private void Update() 
    {
        if (isPlayer)
        {
            m_Object.GetComponent<TMPro.TextMeshProUGUI>().text = SistemaDeTurnos.Instance.Get_Da침oCarta().ToString();
            textoCompleto.SetActive(!SistemaDeTurnos.Instance.Get_TurnoPlayer());
        }
        else
        {
            m_Object.GetComponent<TMPro.TextMeshProUGUI>().text = SistemaDeTurnos.Instance.Get_Da침oCarta().ToString();
            textoCompleto.SetActive(SistemaDeTurnos.Instance.Get_TurnoPlayer());
        }
    }
}